//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyGym.Models;

using QuanLyGym.Models;

namespace QuanLyGym.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoHongHoc
    {
        public string MaTB { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayBao { get; set; }
        public string MoTaSuCo { get; set; }
        public string DonViThucHien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual ThietBiGym ThietBiGym { get; set; }
    }
}

