//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyGym.Models;

namespace QuanLyGym.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiSoInbody
    {
        public string MaInbody { get; set; }
        public Nullable<double> CanNang { get; set; }
        public Nullable<double> ChieuCao { get; set; }
        public Nullable<double> TyLeCo { get; set; }
        public Nullable<double> TyLeMo { get; set; }
        public string MaHV { get; set; }
    
        public virtual HoiVien HoiVien { get; set; }
    }
}

