//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyGym.Models;

namespace QuanLyGym.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoNhanSu
    {
        public string MaHS { get; set; }
        public string TenNV { get; set; }
        public string ChungChi { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public string KhenThuong { get; set; }
        public string MaNV { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}

