//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyGym.Models;

namespace QuanLyGym.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lam
    {
        public string MaNV { get; set; }
        public string MaCa { get; set; }
        public System.DateTime NgayLam { get; set; }
        public Nullable<double> GioLam { get; set; }
    
        public virtual CaLamViec CaLamViec { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}

