//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyGym.Models;

namespace QuanLyGym.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTapLuyen
    {
        public string MaLT { get; set; }
        public Nullable<System.DateTime> NgayTap { get; set; }
        public Nullable<System.TimeSpan> GioTap { get; set; }
        public string TrangThai { get; set; }
        public string MaHV { get; set; }
        public string MaNV { get; set; }
    
        public virtual HoiVien HoiVien { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}

