//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyGym.Models;

namespace QuanLyGym.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChuyenNhuong
    {
        public string MaPCN { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
        public Nullable<decimal> PhiDichVu { get; set; }
        public string MaHV1 { get; set; }
        public string MaHV2 { get; set; }
        public string MaNV { get; set; }
        public string MaHD { get; set; }
    
        public virtual HoiVien HoiVien { get; set; }
        public virtual HoiVien HoiVien1 { get; set; }
        public virtual HopDong HopDong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}

