//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using QuanLyGym.Models;

namespace QuanLyGym.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBiGym
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBiGym()
        {
            this.BaoCaoHongHoc = new HashSet<BaoCaoHongHoc>();
            this.LichBaoTri = new HashSet<LichBaoTri>();
        }
    
        public string MaTB { get; set; }
        public string TenTB { get; set; }
        public string LoaiThietBi { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string TinhTrang { get; set; }
        public string MaLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoCaoHongHoc> BaoCaoHongHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichBaoTri> LichBaoTri { get; set; }
    }
}

